USE IF4101_EXAMEN_B97452;
GO

CREATE PROCEDURE ADMINISTRACION.sp_GET_TYPES_CATEGORIES 
AS
BEGIN
	SELECT [TIPO] FROM [ADMINISTRACION].[tb_CATEGORIA]
END
GO

----------------------------------------------------------

ALTER PROCEDURE ADMINISTRACION.sp_REGISTRAR_ESTANDIAS
	@param_NOMBRE VARCHAR(32),
	@param_PROVINCIA VARCHAR(32),
	@param_DIRECCION VARCHAR(46),
	@param_PRECIO_NOCHE DECIMAL(9,2),
	@param_CAPACIDAD INT,
	--@param_RUTA_IMAGEN VARCHAR(46),
	@param_TIPO_CATEGORIA VARCHAR(42),
	@param_DESCRIPCION VARCHAR(62)
AS
BEGIN
	DECLARE @local_ID_CATEGORIA INT=
								(SELECT 
									 ID
								FROM  [ADMINISTRACION].[tb_CATEGORIA]
									WHERE [TIPO] = @param_TIPO_CATEGORIA)

	INSERT INTO [ADMINISTRACION].[tb_ESTADIA]
	(
	 [NOMBRE], [PROVINCIA], [DIRECCION], [PRECIO_NOCHE], [CAPACIDAD], /*[RUTA_IMAGEN],*/ [ID_CATEGORIA], [DESCRIPCION]
	)
	VALUES(
		@param_NOMBRE,
		@param_PROVINCIA,
		@param_DIRECCION,
		@param_PRECIO_NOCHE,
		@param_CAPACIDAD,
		--@param_RUTA_IMAGEN,
		@local_ID_CATEGORIA,
		@param_DESCRIPCION
	)
END
GO

----------------------------------------------------

ALTER PROCEDURE ADMINISTRACION.sp_GET_ESTADIA_BY_NOMBRE 
	@param_NOMBRE VARCHAR(32)
AS
BEGIN
	SELECT 
		E.[ID], E.[NOMBRE], E.[PROVINCIA], E.[DIRECCION], E.[PRECIO_NOCHE], E.[CAPACIDAD], /*[RUTA_IMAGEN],*/ C.TIPO, E.[DESCRIPCION]
	FROM [ADMINISTRACION].[tb_ESTADIA] E
		JOIN ADMINISTRACION.tb_CATEGORIA C
			ON E.ID_CATEGORIA = C.ID
	WHERE E.[NOMBRE] = @param_NOMBRE AND E.IS_DELETED = 0
END
GO

-----------------------------------------------------

ALTER PROCEDURE ADMINISTRACION.sp_ELIMINAR_ESTADIA 
	@param_ID_ESTANCIA INT
AS
BEGIN
	UPDATE [ADMINISTRACION].[tb_ESTADIA]
		SET [IS_DELETED] = 1
	WHERE ID = @param_ID_ESTANCIA
END
GO

---------------------------------------------------

ALTER TABLE [ADMINISTRACION].[tb_ESTADIA] DROP COLUMN [RUTA_IMAGEN]

--------------------------------------------------

CREATE PROCEDURE ADMINISTRACION.sp_UPDATE_ESTANCIA
	@param_ID INT,
	@param_NOMBRE VARCHAR(32),
	@param_PROVINCIA VARCHAR(32),
	@param_DIRECCION VARCHAR(46),
	@param_PRECIO_NOCHE DECIMAL(9,2),
	@param_CAPACIDAD INT,
	@param_TIPO_CATEGORIA VARCHAR(42),
	@param_DESCRIPCION VARCHAR(62)
AS
BEGIN
	DECLARE @local_ID_CATEGORIA INT=
								(SELECT 
									 ID
								FROM  [ADMINISTRACION].[tb_CATEGORIA]
									WHERE [TIPO] = @param_TIPO_CATEGORIA)

	UPDATE [ADMINISTRACION].[tb_ESTADIA]
	SET [NOMBRE] = @param_NOMBRE,
		[PROVINCIA] = @param_PROVINCIA,
		[DIRECCION] = @param_DIRECCION,
		[PRECIO_NOCHE] = @param_PRECIO_NOCHE,
		[CAPACIDAD] = @param_CAPACIDAD,
		[ID_CATEGORIA] = @local_ID_CATEGORIA,
		[DESCRIPCION] = @param_DESCRIPCION
	WHERE ID = @param_ID 
END
GO

---------------------------------------------------------

ALTER PROCEDURE ADMINISTRACION.sp_GET_CATEGORIES 
AS
BEGIN
	SELECT ID,[TIPO] FROM [ADMINISTRACION].[tb_CATEGORIA]
	WHERE [IS_DELETED] = 0
END
GO

--------------------------------------------------------

ALTER PROCEDURE ADMINISTRACION.sp_REGISTER_CATEGORIA
	@param_TIPO VARCHAR(32)
AS
BEGIN
iF NOT EXISTS (SELECT TIPO FROM [ADMINISTRACION].[tb_CATEGORIA] WHERE TIPO = @param_TIPO)
	BEGIN
		INSERT INTO [ADMINISTRACION].[tb_CATEGORIA]
		(TIPO)VALUES(@param_TIPO)
		RETURN 1;
	END
ELSE
	BEGIN 
		RETURN -1;
	END
END
GO

---------------------------------------------------------

CREATE PROCEDURE ADMINISTRACION.sp_ELIMINAR_CATEGORIA
	@param_ID_CATEGORIA INT
AS
BEGIN
	UPDATE [ADMINISTRACION].[tb_CATEGORIA]
		SET [IS_DELETED] = 1
	WHERE ID = @param_ID_CATEGORIA
END
GO

-------------------------------------------------------

create PROCEDURE ADMINISTRACION.sp_GET_ESTANCIAS
AS
BEGIN
	SELECT 
		E.[ID], E.[NOMBRE], E.[PROVINCIA], E.[DIRECCION], E.[PRECIO_NOCHE], E.[CAPACIDAD], /*[RUTA_IMAGEN],*/ C.TIPO, E.[DESCRIPCION]
	FROM [ADMINISTRACION].[tb_ESTADIA] E
		JOIN ADMINISTRACION.tb_CATEGORIA C
			ON E.ID_CATEGORIA = C.ID
	WHERE E.IS_DELETED = 0
END
GO

-------------------------------------------------------

CREATE PROCEDURE ADMINISTRACION.sp_CONFIRMAR_RESERVA
	@param_ID_ESTANCIA INT,
	@param_CEDULA_CLIENTE VARCHAR(32),
	@param_NOMBRE_COMPLETO VARCHAR(32),
	@param_CANTIAD_PERSONAS INT,
	@param_TELEFONO VARCHAR(43),
	@param_FECHA_ENTRADA DATE,
	@param_FECHA_SALIDA DATE
AS
BEGIN
	IF EXISTS (SELECT [CAPACIDAD] FROM [ADMINISTRACION].[tb_ESTADIA] WHERE ID = @param_ID_ESTANCIA AND [CAPACIDAD] >= @param_CANTIAD_PERSONAS)
		BEGIN 
			INSERT INTO [CLIENTES].[tb_CLIENTE]
			(
				[CEDULA], [NOMBRE_COMPLETO], [TELEFONO_CONTACTO]
			)
			VALUES
			(
				@param_CEDULA_CLIENTE,
				@param_NOMBRE_COMPLETO,
				@param_TELEFONO
			)

			DECLARE @local_ID_CEDULA INT=SCOPE_IDENTITY()

			INSERT INTO [ADMINISTRACION].[tb_RESERVA]
			(
				[ID_ESTADIA], [ID_CLIENTE], [CANTIDAD_PERSONAS], [FECHA_ENTRADA], [FECHA_SALIDA]
			)
			VALUES
			(
				@param_ID_ESTANCIA,
				@local_ID_CEDULA,
				@param_CANTIAD_PERSONAS,
				@param_FECHA_ENTRADA,
				@param_FECHA_SALIDA
			)
			RETURN 1;
		END
	ELSE
		BEGIN
			RETURN -1;
		END
END
GO

